server {
    listen 80;
    server_name id.smarthome.hipahopa.ru id.smarthome.local;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name id.smarthome.local;

    ssl_certificate     /etc/nginx/certs/id.smarthome.local.crt;
    ssl_certificate_key /etc/nginx/certs/id.smarthome.local.key;

    location ~ ^/api/(.*)$ {
        proxy_pass http://auth:8080/$1;

        include /etc/nginx/conf.d/proxy.conf;
    }

    location / {
        proxy_pass http://auth-web;

        include /etc/nginx/conf.d/proxy.conf;
    }
}

server {
    listen 80;
    server_name smarthome.hipahopa.ru smarthome.local;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name smarthome.local;

    ssl_certificate     /etc/nginx/certs/smarthome.local.crt;
    ssl_certificate_key /etc/nginx/certs/smarthome.local.key;

    location ~ ^/api/yandex(.*)$ {
        proxy_pass http://adapter:8080/yandex$1;

        include /etc/nginx/conf.d/proxy.conf;
    }

    location ~ ^/api/panel(.*)$ {
        proxy_pass http://panel-api:8080/panel$1;

        include /etc/nginx/conf.d/proxy.conf;
    }

    location = /api/devices/stream {
        proxy_pass http://devices-api:8080/devices/stream;

        include /etc/nginx/conf.d/proxy.conf;
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 1h;
        proxy_send_timeout 1h;
        chunked_transfer_encoding off;
    }

    location ~ ^/api/devices(.*)$ {
        proxy_pass http://devices-api:8080/devices$1;

        include /etc/nginx/conf.d/proxy.conf;
    }

    location ~ ^/api/chats(.*)$ {
        proxy_pass http://llm-service:8080/chats$1;

        include /etc/nginx/conf.d/proxy.conf;
    }

    location / {
        proxy_pass http://web;

        include /etc/nginx/conf.d/proxy.conf;
    }
}
